name: CI Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - dev

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint src/ --format stylish > code-quality-report.txt

      - name: Run tests with coverage
        run: npm run test -- --coverage

      - name: Check test coverage
        run: |
          COVERAGE_THRESHOLD=80
          COVERAGE=$(npx jest --coverage --coverageReporters=text-summary | grep 'All files' | awk '{print $4}' | sed 's/%//')
          if [ "$COVERAGE" -lt "$COVERAGE_THRESHOLD" ]; then
            echo "Test coverage ($COVERAGE%) is below the threshold ($COVERAGE_THRESHOLD%)"
            exit 1
          fi

      - name: Check code duplication
        run: npx jscpd --min-lines 10 --threshold 5 src/

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage

      - name: Upload code quality report
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-report
          path: code-quality-report.txt

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Copy reports to public directory
        run: |
          mkdir -p public/reports
          cp -r coverage public/reports/
          cp code-quality-report.txt public/reports/

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
